# Generated by Django 5.1.1 on 2024-10-03 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ValidacionResultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='archivos_csv/')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('es_valido', models.BooleanField(default=False)),
                ('mensaje', models.TextField(blank=True)),
            ],
        ),
    ]
